stages:
  - build
  - upload
  - deploy

variables:
  BACKEND_IMAGE_NAME: history-care-backend
  FRONTEND_IMAGE_NAME: history-care-frontend

build:
  stage: build
  tags:
    - deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - docker build -t "$BACKEND_IMAGE_NAME:$CI_COMMIT_SHORT_SHA" backend
    - docker build -t "$FRONTEND_IMAGE_NAME:$CI_COMMIT_SHORT_SHA" frontend

upload:
  stage: upload
  tags:
    - deploy
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - kind load docker-image "$BACKEND_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - kind load docker-image "$FRONTEND_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"

deploy:
  stage: deploy
  tags:
    - deploy
  needs:
    - upload
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - kubectl create configmap history-care-conf --from-file=configs/ --namespace=default -o yaml --dry-run=client | kubectl apply -f -
    - kubectl apply -f manifests/
    - kubectl set image deployment/history-care-backend history-care-backend="$BACKEND_IMAGE_NAME:$CI_COMMIT_SHORT_SHA" migrate="$BACKEND_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - kubectl set image deployment/history-care-frontend history-care-frontend="$FRONTEND_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
    - kubectl rollout status deployment/history-care-backend
    - kubectl rollout status deployment/history-care-frontend
    - kubectl get pods
